export const HALSP_CLI_PLUGIN_TRANSFORMER = "HALSP_CLI_PLUGIN_TRANSFORMER";
export const HALSP_CLI_PLUGIN_PREBUILD = "HALSP_CLI_PLUGIN_PREBUILD";
export const HALSP_CLI_PLUGIN_POSTBUILD = "HALSP_CLI_PLUGIN_POSTBUILD";
export const HALSP_CLI_PLUGIN_ATTACH = "HALSP_CLI_PLUGIN_ATTACH";
export const HALSP_CLI_PLUGIN_CONFIG_HOOK = "HALSP_CLI_PLUGIN_CONFIG_HOOK";
